

services:
  database:
    container_name: database
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: cartradingstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./backend/config/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/config/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - cartradingstore

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: car-trading-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: development
      POSTGRES_HOST: database
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - cartradingstore

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: car-trading-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      INTERNAL_API_BASE: http://backend:4000
      API_URL: http://backend:4000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cartradingstore

  pgadmin:
    image: dpage/pgadmin4
    container_name: car-trading-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - cartradingstore

networks:
  cartradingstore:
    driver: bridge

volumes:
  db:
    driver: local